site_name: Aleksei Ignatev WEB
nav:
 - Home: index.md
 - Lab1:
     - "Task1": lab1/task_1.md
     - "Task2": lab1/task_2.md
     - "Task3": lab1/task_3.md
     - "Task4": lab1/task_4.md
     - "Task5": lab1/task_5.md
 - Lab2:
     - "Task": lab2/task_1.md
 - Lab3:
     - "Task": lab3/index.md
 - Lab4:
     - "Task": lab4/task_1.md
theme:
 name: material